fix: ensure custominspect works for plain objects
chaijs/loupe pull request #38
Opened 2021-02-01 14:43 UTC by keithamus

Mentioned in https://github.com/chaijs/loupe/issues/37#issuecomment-769746796 is that Loupe ignores `customInspect` symbols for "plain" objects. This fixes that.

2021-02-01 14:56 UTC, flaambe commented
I think, we also need to rewrite the ```inspectCustom``` function like in chai, which use recursion, for example for such objects:
```javascript
var obj = {
    outer: {
        inspect: function (depth, options) {
            return options.stylize('Object content', 'string');
        }
    }
};
```

2021-02-01 15:20 UTC, flaambe requested changes

2021-02-01 15:20 UTC, flaambe commented on test/acceptance.js
> +  it('uses custom inspect function is `customInspect` is turned on', () => {
maybe if? :smile:

2021-02-01 17:44 UTC, keithamus commented on test/acceptance.js
> +  it('uses custom inspect function is `customInspect` is turned on', () => {
```suggestion
  it('uses custom inspect function if `customInspect` is turned on', () => {
```

2021-02-01 18:01 UTC, flaambe requested changes
Сould you correct lint errors too, thanks

2021-02-02 11:34 UTC, flaambe approved these changes
LGTM :rocket:

2021-02-02 11:35 UTC, merged